name: PUSH 혹은 PULL_REQUEST 에 테스트 실행.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 현재 브랜치의 소스코드를 가져옵니다.
      - name: Checkout Source Code.
        uses: actions/checkout@v2

      # .nvmrc 파일을 읽어 노드 구동 버전을 가져옵니다.
      - name: Use Node.js.
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      # 패키니 매니저를 Yarn 으로 이용합니다.
      - name: Yarn Project Validate.
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: yarn run validate

      - name: Yarn Project Build.
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: yarn run build

      - name: Listing Build Outputs.
        run: ls -al ./dist
